HW0
alexgol87/topjava pull request #1
Opened 2020-02-05 08:18 UTC by alexgol87

Realization with cycles in two loops

2020-02-05 16:40 UTC, przrak requested changes

2020-02-05 16:40 UTC, przrak commented on src/main/java/ru/javawebinar/topjava/util/UserMealsUtil.java
> +        meals.forEach(userMeal -> {
сделай с одним if'ом, два как то слишком жестко выглядят

2020-02-05 16:40 UTC, przrak commented on src/main/java/ru/javawebinar/topjava/util/UserMealsUtil.java
>      public static List<UserMealWithExcess> filteredByCycles(List<UserMeal> meals, LocalTime startTime, LocalTime endTime, int caloriesPerDay) {
название для метода поменяй на filteredByLoop, к примеру

2020-02-05 16:40 UTC, przrak commented on src/main/java/ru/javawebinar/topjava/util/UserMealsUtil.java
> +                caloriesExceed.set(true);
caloriesExceed считай не через true, false. Передавай туда выражение, которое либо true либо false, тогда как раз избавишься от второго if блока

2020-02-05 17:02 UTC, alexgol87 commented on src/main/java/ru/javawebinar/topjava/util/UserMealsUtil.java
> +                caloriesExceed.set(true);
Уже реализовал в варианте со стримами) Сначала не допёр.

2020-02-07 06:38 UTC, przrak approved these changes

2020-02-07 13:44 UTC, merged